server.port=8081
spring.application.name=rest

spring.datasource.url=jdbc:postgresql://localhost:5432/projet_al
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
