server.port=8080
spring.application.name=site

spring.datasource.url=jdbc:postgresql://localhost:5432/projet_al
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
